language: java
jdk: oraclejdk8

# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify
  - |
  mvn sonar:sonar \
    -Dsonar.projectKey=BenjaminPeltier_sample-application-students \
    -Dsonar.organization=benjaminpeltier-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=$SONAR_TOKEN

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
    - secure: HOImjihkxvleFu96O4MSpZLhUfXkAsB2dlkXThBMPmZ3qAx7z4BrFyN02PWHxHOYe+MR/0TWY/D4XNcOyBGhfwYCPSaH1wXdQQWIVzR6FRbUOD979532sDDD0biDyICCdizAl6XYketl4oui/CXl656Rt5SQ1fFc1W/O99Pbssk2ZVK2Mm3Ln8jHxmszQneZmKlwewvi/XNwImhxfS7w2ioO+k+L0g7UEdPxVrqqPQNn4oo3rsey/rQn8Dj4gx/JFa29J7WC4MH+1KkCmfA5bJpIRkZ/1mAMP54pXM1jxzZiLmwwbJiRSL/AbpwOPbVVuFahjHQQqzYTZX2L2nNnXUy4oIl0br1MQXjH4GYQxH1AMLCMFA+FRdn36RhhrqkIW5kdPH4MAEDg0s4UEMNa7oWvwaq+pr30+TOaAfGnNGVIQXG7+sCWTDLqS/Cs4iITUFX5STWGhdP2cTX8zMsqtiqCw+sP2HzVXs0cdMjYgbMMGelACDBp9KApJh4aoclseY4cudN7XY2E7AL3eXHXZ+LS1vPUdBWhXf2RbssmRKvsBnHgRH96pPFySQ1oWwzFUmmBTV0mWNPOG9/gPdV+h4vw8KhpfELFMUmlf6n5P1WwE/aV8kgUuZBiagakvKmi1hzxFnoscPcleii0rWeyvpGERg56tt1NtvLtsJIa8Ak=
